# Generated by Django 5.1.4 on 2025-01-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='acct_type',
            field=models.CharField(default='regular', max_length=25),
        ),
    ]
