# Generated by Django 5.1.4 on 2025-01-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orderitem_business_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_location',
            field=models.CharField(default='Lagos, Nigeria', max_length=30),
        ),
    ]
