# Generated by Django 5.1.4 on 2025-01-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_description',
            field=models.TextField(null=True),
        ),
    ]
