# Generated by Django 5.1.4 on 2025-01-30 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_date_added_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 10, 51, 39, 416941)),
        ),
    ]
