# Generated by Django 5.1.5 on 2025-03-02 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_date_added_remove_wishlist_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 14, 37, 38, 367995)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.JSONField(null=True),
        ),
    ]
