# Generated by Django 5.1.5 on 2025-03-02 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_date_added_alter_wishlist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 14, 48, 36, 606571)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.JSONField(default=dict),
        ),
    ]
