# Generated by Django 5.1.5 on 2025-03-06 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 17, 21, 36, 391071)),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.JSONField(default=dict),
        ),
    ]
